### PR TITLE
Leave unhandled rooms

### PR DESCRIPTION
**Pull request by Half-Shot**
As a potential fix to https://github.com/matrix-org/matrix-appservice-gitter/issues/63

### CODE REVIEW

**Comment by Half-Shot** [comment]
(Gah, review and assign look the same :disappointed: )
Advise on how sane this looks, potentially dangerous in the wild but hopefully will save us some AS cycle time and users who find the bot won't leave the room.

**Review by lukebarnard1 — APPROVED** [review]
I *think* this looks fine although the logic above is quite subtle in that both returning early and `handled` represent successful handling, where "handling" could be doing nothing. But that's not your fault ;)

Could do with some logging that doesn't look identical to " ... ignore". Other than that, LGTM.

**Comment by Half-Shot** [comment]
I am quite worried by handled because handled != interested. Really we should have a flag for determining if we are interested and handled is a separate thing about whether we handled the event successfully.

**Comment by SISheogorath** [comment]
I would definitely love to see the gitter bot to leave the channel, when its no longer used for bridging. Currently I have a room where I recently removed all gitter bridges but the bot is still around and has dangerously high privileges.

**Pull request closed without merging**
